import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import AnimatedBackgroundPro from "@/components/ui/AnimatedBackground";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/navbar/logo.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative text-white">
        <Navbar/>
        <AnimatedBackgroundPro/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
